# renew_before_expiry = 30 days
version = 1.21.0
archive_dir = /root/profile-butcher/certbot/conf/archive/biologischvleeschatelier.profile.elysia.marketing
cert = /root/profile-butcher/certbot/conf/live/biologischvleeschatelier.profile.elysia.marketing/cert.pem
privkey = /root/profile-butcher/certbot/conf/live/biologischvleeschatelier.profile.elysia.marketing/privkey.pem
chain = /root/profile-butcher/certbot/conf/live/biologischvleeschatelier.profile.elysia.marketing/chain.pem
fullchain = /root/profile-butcher/certbot/conf/live/biologischvleeschatelier.profile.elysia.marketing/fullchain.pem
[renewalparams]
account = a6dc0555fd8e2c11f212f654bc1a092b
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
config_dir = /root/profile-butcher/certbot/conf
work_dir = /root/profile-butcher/certbot/work
logs_dir = /root/profile-butcher/certbot/logs
